policies:
  - name: assign MR
    resource: merge_request
    conditions:
      date:
        attribute: created_at
        condition: older_than
        intervalType: days
        interval: 10
      state: opened
      milestone: v1
      labels:
        - label 1
        - label 2
      forbiddenLabels:
        - label 3
      discussion:
        attribute: threads
        condition: less_than
        threshold: 15
    limit:
      mostRecent: 50
    actions:
      http:
        once: true
        method: post
        endpoint: /project/:id/approval_merge
        iterate:
          attribute: user_id
      labels:
        - needs work
      removeLabels:
        - done
      status: close
      mention:
        - someone
        - someone2
      comment: |
        Closing this issue, thanks for the fix {{author}}
  - name: Second thing
    resource: note
    conditions:
      state: opened
      labels:
        - label 1
        - label 2
    limit:
      oldest: 5
    actions:
      labels:
        - needs work
      removeLabels:
        - done
      status: close
      mention:
        - someone
        - someone2
      comment: |
        Closing this issue, thanks for the fix {{author}}