policies:
  - name: assign MR
    resource: Merge Request Hook
    conditions:
      date:
        attribute: created_at
        condition: older_than
        intervalType: days
        interval: 10
      state:
        - open
        - updated
      milestone: 6
      labels:
        - label 1
        - label 2
      forbiddenLabels:
        - label 3
      discussion:
        attribute: threads
        condition: less_than
        threshold: 15
    limit:
      mostRecent: 50
    actions:
      labels:
        - needs work
      removeLabels:
        - done
      status: close
      mention:
        - someone
        - someone2
      comment: |
        Closing this issue, thanks for the fix {{author}}
  - name: Second thing
    resource: Merge Request Hook
    conditions:
      labels:
        - label 1
        - label 2
    limit:
      oldest: 5
    actions:
      labels:
        - needs work
      removeLabels:
        - done
      status: close
      mention:
        - someone
        - someone2
      comment: |
        Closing this issue, thanks for the fix {{author}}