name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Vet
      run: go vet ./...

    - name: Shadow
      run: go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest && shadow ./...

    - name: Test
      run: go test -v ./... -race -covermode=atomic -coverprofile=coverage.out

    - name: Go report card
      uses: creekorful/goreportcard-action@v1.0
      
    - uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODE_COV }}
        files: coverage.out
