variables:
  REPO_NAME: gitlab.com/jonny7/quetzal

services:
  - docker:20.10.12-dind

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test
  - requirements
  - publish

quetzal:test:
  image: golang:1.17.5
  stage: test
  script:
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -v ./... -race -covermode=atomic -coverprofile=coverage.out
    - go install github.com/jstemmer/go-junit-report@latest
    - go test -v ./... 2>&1 | go-junit-report > report.xml
    - go install honnef.co/go/tools/cmd/staticcheck@latest
    - staticcheck ./...
  artifacts:
    when: always
    paths:
      - report.xml
    reports:
      junit: report.xml

requirements:check:
  image: golang:1.17.5
  stage: requirements
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - go get -u gitlab.com/jonny7/gitlab-matrix-generator
    - go build -o matrix gitlab.com/jonny7/gitlab-matrix-generator/cmd
    - ./matrix
  dependencies:
    - quetzal:test
  artifacts:
    when: always
    reports:
      requirements: requirements.json
    paths:
      - requirements-matrix.csv

quetzal:publish:
  image: docker:20.10.11
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo -n $CI_REGISTRY_TOKEN | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - docker build --build-arg version=$CI_COMMIT_TAG -t $CI_REGISTRY_USER/quetzal:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_USER/quetzal:$CI_COMMIT_TAG
  dependencies:
    - quetzal:test
  needs:
    ["quetzal:test"]