image: golang:latest

variables:
  REPO_NAME: gitlab.com/jonny7/quetzal

before_script:
  - mkdir -p $GOPATH/src/$(dirname $REPO_NAME)
  - ln -svf $CI_PROJECT_DIR $GOPATH/src/$REPO_NAME
  - cd $GOPATH/src/$REPO_NAME

stages:
  - test

quetzal:test:
  stage: test
  script:
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -v $(go list ./... | grep -v /cmd/matrix/) -race -covermode=atomic -coverprofile=coverage.out
    - go install github.com/jstemmer/go-junit-report@latest
    - go test -v ./... 2>&1 | go-junit-report > report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml

requirements:check:
  stage: test
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - ls
    - go build -o matrix ./cmd/matrix
    - ./matrix
  dependencies:
    - quetzal:test
  artifacts:
    when: always
    reports:
      requirements: requirements.json
    paths:
      - requirements-matrix.csv
